Repository MiSArch/docs, pull requests merged in 2024-03, with the labels that each got.

#84 Document how to add a new service to the K8s deployment
  docs/docs/dev-manuals/kubernetes/_category_.json
  docs/docs/dev-manuals/kubernetes/adding-a-new-service.md
  docs/docs/install-manuals/publishing-keycloak.md
Labels: documentation

#88 Update completion status
  diagrams/domainModel.hyl
  diagrams/domainModelBC.hyl
  diagrams/domainModelCompletionStatus.hyl
Labels: documentation

#95 Add ADR how health endpoints look like
  docs/docs/dev-manuals/adr/0010-health-endpoint.md
  docs/docs/dev-manuals/architecture/component-diagram.mdx
  docs/docs/dev-manuals/architecture/health-endpoints.md
Labels: ADR

#101 update domain model
  diagrams/catalogDomainModel.hyl
  diagrams/domainModel.hyl
  diagrams/domainModelBC.hyl
  diagrams/domainModelCompletionStatus.hyl
Labels: enhancement

#111 Update completion state diagrams
  diagrams/domainModel.hyl
  diagrams/domainModelBC.hyl
  diagrams/domainModelCompletionStatus.hyl
Labels: enhancement

#126 Document specifics about the K8s setup
  docs/docs/dev-manuals/services/infrastructure-k8s.md
Labels: documentation
