Repository MiSArch/docs, pull requests merged in 2024-01, with the labels that each got.

#17 Add first user journeys
  docs/dev-manuals/architecture/user-journeys.md
  static/diagrams/journey-adding-product-dark.svg
  static/diagrams/journey-adding-product-light.svg
  static/diagrams/journey-adding-product-variants-dark.svg
  static/diagrams/journey-adding-product-variants-light.svg
  static/diagrams/journey-adding-to-wishlist-dark.svg
  static/diagrams/journey-adding-to-wishlist-light.svg
  static/diagrams/journey-browsing-dark.svg
  static/diagrams/journey-browsing-light.svg
  static/diagrams/journey-checking-dark.svg
  static/diagrams/journey-checking-light.svg
  static/diagrams/journey-looking-2-dark.svg
  static/diagrams/journey-looking-2-light.svg
  static/diagrams/journey-looking-dark.svg
  static/diagrams/journey-looking-light.svg
  static/diagrams/journey-ordering-dark.svg
  static/diagrams/journey-ordering-light.svg
  static/diagrams/journey-returning-dark.svg
  static/diagrams/journey-returning-light.svg
  static/diagrams/journey-wishlist-dark.svg
  static/diagrams/journey-wishlist-light.svg
  static/diagrams/journey-writing-review-2-dark.svg
  static/diagrams/journey-writing-review-2-light.svg
  static/diagrams/journey-writing-review-dark.svg
  static/diagrams/journey-writing-review-light.svg
Labels: documentation

#27 ADR: How do we define storypoints?
  docs/dev-manuals/adr/0008-storypoints.md
  docusaurus.config.js
  package-lock.json
  package.json
Labels: ADR

#28 add ADR for entity consistency
  docs/dev-manuals/adr/0009-check-entity-consistency.md
Labels: ADR

#31 Fix image handling
  docs/dev-manuals/architecture/business-processes.md
  docs/dev-manuals/architecture/component-dependencies.md
  docs/dev-manuals/architecture/component-diagram.md
  docs/dev-manuals/architecture/domain-model.mdx
  docs/dev-manuals/architecture/experiment-configuration.mdx
  docs/dev-manuals/tooling/techstack-and-service-creation.md
  image-sources/diagrams/purchase-interaction-sequence.mermaid
  image-sources/images/techstack-overview.drawio
  src/pages/index.js
  static/diagrams/purchase-interaction-sequence-dark.svg
  static/diagrams/purchase-interaction-sequence-light.svg
  static/images/experiment-configuration-sequence-diagram-light.svg
Labels: bug

#34 Bring component statuses up to date
  diagrams/domainModel.hyl
  diagrams/domainModelBC.hyl
  diagrams/domainModelCompletionStatus.hyl
Labels: enhancement

#35 Inventory is not yet finished
  diagrams/domainModel.hyl
  diagrams/domainModelBC.hyl
  diagrams/domainModelCompletionStatus.hyl
Labels: bug

#36 Add Misarch logos
  docusaurus.config.js
  static/icons/misarch-logo-dark.svg
  static/icons/misarch-logo.jpg
  static/icons/misarch-logo.svg
Labels: enhancement
